const clientMainPage = [
  {
    name: "Chattr",
    backgroundImage: "/images/clients/chattr/testimonial-bg.png",
    industry: "Technology",
    slug: "chattr",
    backgroundColor: "#36ad8b",
  },
  {
    name: "Carro",
    backgroundImage: "/images/clients/carro/testimonial-bg.png",
    industry: "Technology",
    slug: "carro",
    backgroundColor: "#93469a",
  },
  {
    name: "Blockchain Education Network",
    backgroundImage: "/images/clients/ben/testimonial-bg.png",
    industry: "Non-profit",
    slug: "ben",
    backgroundColor: "#ff936b",
  },
  {
    name: "Homewatch Amelia",
    backgroundImage: "/images/clients/amelia/testimonial-bg.png",
    industry: "Home Service",
    slug: "amelia",
    backgroundColor: "#4f80c2",
  },
  {
    name: "Bobtail",
    backgroundImage: "/images/clients/bobtail/testimonial-bg.png",
    industry: "Technology",
    slug: "bobtail",
    backgroundColor: "#f6a326",
  },
  {
    name: "Magnetite",
    backgroundImage: "/images/clients/magnetite/testimonial-bg.png",
    industry: "Home Service",
    slug: "magnetite",
    backgroundColor: "#46b7e6",
  },
  {
    name: "Go-Cottage",
    backgroundImage: "/images/clients/go-cottage/testimonial-bg.png",
    industry: "Real Estate",
    slug: "go-cottage",
    backgroundColor: "#B3D079",
  },
  {
    name: "The HID Factory",
    backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
    industry: "Automotive",
    slug: "the-hid-factory",
    backgroundColor: "#26a8f6",
  },
  {
    name: "CarTalk Repair",
    backgroundImage: "/images/clients/cartalk/testimonial-bg.jpg",
    industry: "Automotive",
    slug: "cartalk-repair",
    backgroundColor: "#bf1e2e",
  },
  {
    name: "The Blue Collar Success Group",
    backgroundImage: "/images/clients/bluecollar/testimonial-bg.jpg",
    industry: "Home Service",
    slug: "bluecollar",
    backgroundColor: "#0a98cc",
  },
  {
    name: "AWP Delivers",
    backgroundImage: "/images/clients/awp/testimonial-bg.jpg",
    industry: "Automotive",
    slug: "awp",
    backgroundColor: "#476cb1",
  },
  // {
  //   name: "Zexster",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Technology",
  //   slug: "zexster",
  //   backgroundColor: "#0780ff",
  // },
  // {
  //   name: "Lessons That Rock",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Music",
  //   slug: "lessons-that-rock",
  //   backgroundColor: "#20bef0",
  // },
  // {
  //   name: "Safe-Dry",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "safe-dry",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "HBP",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "hbp",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Pennies for Education and Health",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "peh",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Reflections Therapy",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "reflections-therapy",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Moeller's Bakery",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "moellers-bakery",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Fireside Investments",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "fireside-investments",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Player Boost",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "player-boost",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Popbowl",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "popbowl",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Oklahoma On Demand",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "oklahoma-on-demand",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "AJ Locksmith",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "aj-locksmith",
  //   backgroundColor: "#26a8f6",
  // },
  // {
  //   name: "Kerry Hart",
  //   backgroundImage: "/images/clients/the-hid-factory/testimonial-bg.png",
  //   industry: "Automotive",
  //   slug: "kerry-hart",
  //   backgroundColor: "#26a8f6",
  // },
];
export default clientMainPage;
